### ISSUE TITLE
Day 33 Lab - App crashes when I try to run it.

### ISSUE THREAD

**Issue by elaewin** [luayyounus/CoreDataHotel#14]
Make sure that if you've added files to your project, you've added them to the project directly, and are not just linking to the files in another location on your hard drive. The `CoreDataSaveFetch` files are linked to your project that way, which means that they are not included in the project on your repo, and the fact that they are missing is causing your app to crash when I run it on my machine.

**Comment by luyounus** [comment]
Fixed
