### ISSUE TITLE
Day 32 Lab - Missing technical requirements

### ISSUE THREAD

**Issue by elaewin** [luayyounus/CoreDataHotel#9]
Your are still missing the following technical requirements:

* Create a new UIViewController subclass called `DatePickerViewController` to allow the user to book reservations for specific timeframe.  
    * **You have these, but without some kind of label, it's hard to tell what the pickers are for, and it's unclear that certain dates are not allowed.**
  
* Upon selecting a room on the `RoomAvailabilityViewController`, the user should transition to another viewController called `BookViewController` where they can enter all the information needed to book a reservation for this room.  
    * **Implement a `Done` button to allow the user to book the reservation.**  
    * **The `selector` for this button should create a new `Reservation` and persist it to Core Data.**

**Comment by luyounus** [comment]
Completed the missing technical requirements.
